services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: streaming_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - streamflow-frontend

  nginx:
    container_name: streamflow-frontend-nginx
    build: ../nginx
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=8000
      - FRONTEND_HOST=host.docker.internal
      - FRONTEND_PORT=5173
      - STORAGE_HOST=storage
      - STORAGE_PORT=9000
    ports:
      - "80:80"
      - "9000:9000"
    networks:
      - streamflow-frontend

  backend:
    container_name: backend
    build: ../backend
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@postgres:5432/streaming_db
      - MINIO_ENDPOINT=storage:9000
      - MINIO_ACCESSKEY=minioadmin
      - MINIO_SECRETKEY=minioadmin
      - MINIO_BUCKET=dev
    depends_on:
      - postgres
      - storage
    networks:
      - streamflow-frontend

  media-server:
    container_name: media_server
    build: ../media_server
    command: nginx -c /etc/nginx/nginx.dev.conf -g 'daemon off;'
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - hls_data:/tmp/hls
    depends_on:
      - backend
    networks:
      - streamflow-frontend

  storage:
    image: minio/minio
    container_name: streamflow-storage
    command: server /data --console-address ":9090"
    restart: always
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    networks:
      - streamflow-frontend

volumes:
  postgres_data:
  hls_data:
  minio_data:

networks:
  streamflow-frontend: