services:
  postgres:
    image: postgres:15-alpine
    container_name: streamflow-db
    ports:
      - "9999:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: streaming_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  media-server:
    container_name: streamflow-media
    build: ../media_server
    command: nginx -c /etc/nginx/nginx.dev.conf -g 'daemon off;'
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - hls_data:/tmp/hls

  frontend:
    container_name: streamflow-frontend
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:8000

volumes:
  postgres_data:
  hls_data: