"""fix_birthday_field_in_user

Revision ID: 9cb5bb1e9e49
Revises: 5d87b4737297
Create Date: 2025-11-16 15:34:10.544029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9cb5bb1e9e49'
down_revision: Union[str, None] = '5d87b4737297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.DateTime(),
               type_=sa.Date(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.Date(),
               type_=sa.DateTime(),
               existing_nullable=True)
    # ### end Alembic commands ###