"""add-role-column-to-user

Revision ID: 7b509f342cd9
Revises: 001
Create Date: 2025-10-18 18:30:04.763464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '7b509f342cd9'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
	op.create_table(
		'roles',
		sa.Column('id', sa.Integer(), primary_key=True),
		sa.Column('name', sa.String(length=255), nullable=False),
		sa.PrimaryKeyConstraint('id')
	)

	op.create_table(
		'user_role',
		sa.Column('id', sa.UUID(), nullable=False),
		sa.Column('user_id', sa.UUID(), nullable=False),
		sa.Column('role_id', sa.Integer(), nullable=False),
		sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
		sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
		sa.PrimaryKeyConstraint('id')
	)

	op.create_index('ix_user_role_user_id', 'user_role', ['user_id'], unique=False)
	op.create_index('ix_user_role_role_id', 'user_role', ['role_id'], unique=False)


def downgrade() -> None:
	# ### commands auto generated by Alembic - please adjust! ###
	# ### end Alembic commands ###
	op.drop_index('ix_user_role_user_id', table_name='user_role')
	op.drop_index('ix_user_role_role_id', table_name='user_role')
	op.drop_table('user_role')

	op.drop_table('roles')
