"""apply alembic fixes

Revision ID: 5d87b4737297
Revises: 163b39b02dfa
Create Date: 2025-11-16 15:31:32.970157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d87b4737297'
down_revision: Union[str, None] = '163b39b02dfa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stream_theme', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_stream_theme_stream_id', table_name='stream_theme')
    op.drop_index('ix_stream_theme_theme_id', table_name='stream_theme')
    op.drop_index('ix_streams_user_id', table_name='streams')
    op.create_index(op.f('ix_streams_stream_key'), 'streams', ['stream_key'], unique=True)
    op.alter_column('themes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_themes_name', table_name='themes')
    op.drop_index('ix_user_role_role_id', table_name='user_role')
    op.drop_index('ix_user_role_user_id', table_name='user_role')
    op.alter_column('user_theme', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index('ix_user_theme_theme_id', table_name='user_theme')
    op.drop_index('ix_user_theme_user_id', table_name='user_theme')
    op.drop_index('ix_user_theme_user_theme', table_name='user_theme')
    op.alter_column('users', 'date_of_birth',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'date_of_birth',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.create_index('ix_user_theme_user_theme', 'user_theme', ['user_id', 'theme_id'], unique=True)
    op.create_index('ix_user_theme_user_id', 'user_theme', ['user_id'], unique=False)
    op.create_index('ix_user_theme_theme_id', 'user_theme', ['theme_id'], unique=False)
    op.alter_column('user_theme', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index('ix_user_role_user_id', 'user_role', ['user_id'], unique=False)
    op.create_index('ix_user_role_role_id', 'user_role', ['role_id'], unique=False)
    op.create_index('ix_themes_name', 'themes', ['name'], unique=False)
    op.alter_column('themes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_streams_stream_key'), table_name='streams')
    op.create_index('ix_streams_user_id', 'streams', ['user_id'], unique=False)
    op.create_index('ix_stream_theme_theme_id', 'stream_theme', ['theme_id'], unique=False)
    op.create_index('ix_stream_theme_stream_id', 'stream_theme', ['stream_id'], unique=False)
    op.alter_column('stream_theme', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###